### ISSUE TITLE
unzipmirror stop at Extracting...

### ISSUE THREAD

**Issue by chhayse7en** [anasty17/mirror-leech-telegram-bot#410]
With your latest update. The unzipmirror function seems to stop working properly. Hope u can fix this. Thanks!

**Comment by anasty17** [comment]
@chhayse7en Logs

**Comment by anasty17** [comment]
Fixed

**Comment by chhayse7en** [comment]
The problem still persist. here is the logs.
[logs.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/8152015/logs.txt)

**Comment by anasty17** [comment]
@chhayse7en Will fix

**Comment by anasty17** [comment]
Try now
